-- Números legibles: ALQ-0001 (contrato), LIQ-0001 (liquidación). Los
-- recibos ya tenían receipt_number (R-0001). Los existentes se numeran por
-- orden de alta; los nuevos siguen solos por identity.
alter table public.rental_contracts add column number bigint;
update public.rental_contracts c set number = n.rn
from (select id, row_number() over (order by created_at, id) rn from public.rental_contracts) n where n.id = c.id;
alter table public.rental_contracts alter column number set not null;
alter table public.rental_contracts add constraint rental_contracts_number_key unique (number);
do $$ declare v_next bigint; begin
  select coalesce(max(number), 0) + 1 into v_next from public.rental_contracts;
  execute format('alter table public.rental_contracts alter column number add generated by default as identity (start with %s)', v_next);
end $$;

alter table public.rental_settlements add column number bigint;
update public.rental_settlements s set number = n.rn
from (select id, row_number() over (order by issued_at, id) rn from public.rental_settlements) n where n.id = s.id;
alter table public.rental_settlements alter column number set not null;
alter table public.rental_settlements add constraint rental_settlements_number_key unique (number);
do $$ declare v_next bigint; begin
  select coalesce(max(number), 0) + 1 into v_next from public.rental_settlements;
  execute format('alter table public.rental_settlements alter column number add generated by default as identity (start with %s)', v_next);
end $$;

-- El historial usa el mismo código de recibo que el resto de la app.
create or replace function public.rental_log_payment_entry() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  r record := case when tg_op = 'DELETE' then old else new end;
  v_charge record;
begin
  select ch.contract_id, ch.description, ch.currency into v_charge from rental_charges ch where ch.id = r.charge_id;
  if v_charge.contract_id is null then return r; end if;
  if tg_op = 'INSERT' then
    insert into rental_activity (contract_id, actor_kind, actor_agent_id, action, detail, amount, currency, ref_id)
    values (v_charge.contract_id, case when auth.uid() is null then 'SISTEMA' else 'AGENTE' end, auth.uid(),
      case when new.inbox_id is not null then 'PAGO_CONFIRMADO' else 'COBRO_REGISTRADO' end,
      case when new.inbox_id is not null then 'Confirmó e imputó a ' else 'Registró un cobro de ' end || v_charge.description
        || ' · recibo R-' || lpad(new.receipt_number::text, 4, '0')
        || case when new.bank_movement_id is not null then ' · conciliado con el banco' else '' end,
      new.amount, v_charge.currency, new.id);
  else
    insert into rental_activity (contract_id, actor_kind, actor_agent_id, action, detail, amount, currency, ref_id)
    values (v_charge.contract_id, case when auth.uid() is null then 'SISTEMA' else 'AGENTE' end, auth.uid(), 'COBRO_ANULADO',
      'Anuló el cobro de ' || v_charge.description || ' · recibo R-' || lpad(old.receipt_number::text, 4, '0'),
      old.amount, v_charge.currency, old.id);
  end if;
  return r;
end $$;
revoke execute on function public.rental_log_payment_entry() from public, anon, authenticated;

update public.rental_activity set detail = regexp_replace(detail, 'recibo N\.º (\d+)', 'recibo R-' || 'X\1')
where detail ~ 'recibo N\.º \d+';
update public.rental_activity set detail = regexp_replace(detail, 'R-X(\d+)', 'R-' || lpad(substring(detail from 'R-X(\d+)'), 4, '0'))
where detail ~ 'R-X\d+';
